---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.KEYCLOAK_ADMIN_PASSWD }}
  DB_USER: "keycloak"
  DB_PASSWORD: {{ .Values.keycloak.KEYCLOAK_DB_PASSWD }}
