---
apiVersion: v1
kind: Secret
metadata:
  name: rmf-web-rmf-server-secret
type: Opaque
stringData:
  DB_USER: "rmf-web-rmf-server"
  DB_PASSWORD: {{ .Values.rmf_web.API_SERVER_DB_PASSWD | quote }}
  ADMIN_PASSWD: {{ .Values.rmf_web.ADMIN_PASSWD }}
