{{- if .Values.ENABLE_RMF_SIM -}}
---
apiVersion: v1
kind: Service
metadata:
  name: rmf-sim
  labels:
    app: rmf-sim
spec:
  selector:
    app: rmf-sim
  ports:
    - protocol: TCP
      port: 8006
      targetPort: 8006
      name: websocket-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmf-sim
  labels:
    app: rmf-sim
spec:
  selector:
    matchLabels:
      app: rmf-sim
  template:
    metadata:
      labels:
        app: rmf-sim
    spec:
      containers:
        - name: rmf-sim
          image: {{ .Values.global.REGISTRY_RMF | default "localhost" }}/{{ .Values.rmf_sim.RMF_SIM_IMAGE }}:{{ .Values.global.DEPLOYMENT_IMAGE_TAG }}
          imagePullPolicy: IfNotPresent
          env:
            - name: RMF_USE_SIM_TIME
              value: {{ .Values.global.RMF_USE_SIM_TIME | quote }}
            - name: {{ .Values.global.DDS_ENV | quote }}
              value: {{ .Values.global.DDS_CONFIG | quote }}
            - name: ROS_DOMAIN_ID
              value: {{ .Values.global.ROS_DOMAIN_ID | quote }}
            - name: RMW_IMPLEMENTATION
              value: {{ .Values.global.RMW_IMPLEMENTATION | quote }}
          command: ["/bin/bash"]
          args:
            - -c
            - >
              export JWT_PUBLIC_KEY="$(cat /etc/config/jwt-pub-key.pub)"; /ros_entrypoint.sh
              ros2 launch {{ .Values.rmf_sim.RMF_SIM_PACKAGE }} {{ .Values.rmf_sim.RMF_SIM_LAUNCH_FILE }}
              headless:=true
              use_sim_time:={{ .Values.global.RMF_USE_SIM_TIME }}
              failover_mode:={{ .Values.global.RMF_FAILOVER_MODE }}
              server_uri:={{ .Values.global.RMF_SERVER_URI }}
          ports:
            - containerPort: 8006
              name: websocket-port
              protocol: TCP
          volumeMounts:
            - mountPath: {{ .Values.global.DDS_CONFIG_MOUNTPATH | quote }}
              name: {{ .Values.global.DDS_CONFIG_VOLUME | quote }}
            - mountPath: /etc/config
              name: jwt-pub-key
              readOnly: true
      volumes:
        - name: {{ .Values.global.DDS_CONFIG_VOLUME | quote }}
          configMap:
            name: {{ .Values.global.DDS_CONFIG_VOLUME | quote }}
        - name: jwt-pub-key
          configMap:
            name: jwt-pub-key
      tolerations:
        - key: reserved
          operator: Equal
          value: rmf
          effect: NoSchedule
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rmf-sim
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: {{ .Values.CERT_MANAGER_ISSUER }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.hostName | quote }}
      http:
        paths:
          - path: /trajectory
            pathType: Prefix
            backend:
              service:
                name: rmf-sim
                port:
                  number: 8006
  tls:
    - hosts:
        - {{ .Values.hostName | quote }}
      secretName: rmf-sim-ingress-tls
{{- end -}}
