---
apiVersion: v1
kind: Namespace
metadata:
  name: rmf
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rmf-dev-ca
  namespace: infra
spec:
  isCA: true
  commonName: rmf-dev
  secretName: rmf-dev-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: rmf-dev-issuer
spec:
  ca:
    secretName: rmf-dev-secret
